---


- hosts: all
  become: true
  tasks:
    - name: updating apt index
      apt:
        update_cache: yes
    - name: install apache
      apt:
        name: apache2
        # use absent in state to delete it
        state: latest
